apiVersion: v1
kind: Service
metadata: 
  name: mongodb
spec:
  selector:
    app: mongodb
  ports:
   - port: 27017
  type: ClusterIP

---

apiVersion: v1
kind: Service
metadata: 
  name: rotten-potatoes
spec:
  selector:
    app: rotten-potatoes
  ports:
   - port: 5000
     #- port: 80
     #  targetPort: 5000
     # #  protocol: TCP
     # #  name: ui
     nodePort: 30000
  type: NodePort
  #type: ClusterIP
 